imports:
- path: customnetwork-template.jinja
- path: subnetwork-template.jinja
- path: firewall-template.jinja

resources:
# GCP Custom Network
- name: custom-network
  type: customnetwork-template.jinja

# GCP Subnets (us-central, canada, uk and mumbai)
- name: subnetworks
  type: subnetwork-template.jinja
  properties:
    network: $(ref.custom-network.selfLink)
    subnets:
      - range: 20.0.0.0/20
        region: us-west1
        name: subnet-1

# GCP Firewall Rules
- name: custom-network-allow-http-ssh-rdp
  type: firewall-template.jinja
  properties:
    network: $(ref.custom-network.selfLink)
    IPProtocol: TCP
    Port: [22, 80, 443]

- name: custom-network-allow-icmp
  type: firewall-template.jinja
  properties:
    network: $(ref.custom-network.selfLink)
    IPProtocol: ICMP
    Port: []
