imports:
- path: customnetwork-template.jinja
- path: subnetwork-template.jinja
- path: firewall-template.jinja
- path: route-template.jinja

resources:
# GCP Custom Network
- name: boomi-network
  type: customnetwork-template.jinja

# GCP Subnets (us-central, canada, uk and mumbai)
- name: boomi-network-subnet-us
  type: subnetwork-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    subnets:
    - name: private-subnet-1
      ipCidrRange: 10.130.0.0/20
      region: us-central1
    - name: private-subnet-2
      ipCidrRange: 10.130.16.0/20
      region: us-east4
    - name: private-subnet-3
      ipCidrRange: 10.130.32.0/20
      region: europe-west2
    - name: private-subnet-4
      ipCidrRange: 10.130.48.0/20
      region: asia-south1

# GCP Route
- name: boomi-network-route
  type: route-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    use_custom_network: true
    region: us-east4

# GCP Firewall Rules
- name: boomi-network-allow-http-ssh-rdp
  type: firewall-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    IPProtocol: TCP
    Port: [22, 80, 443]

- name: boomi-network-allow-icmp
  type: firewall-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    IPProtocol: ICMP
    Port: []
