imports:
- path: customnetwork-template.jinja
- path: subnetwork-template.jinja
- path: firewall-template.jinja

resources:
# GCP Custom Network
- name: boomi-network
  type: customnetwork-template.jinja

# GCP Subnets (us-central, canada, uk and mumbai)
- name: boomi-network-subnet-us
  type: subnetwork-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    subnets:
      name: private-subnet-1
      ipCidrRange: 10.130.0.0/20
      region: us-central1

# GCP Firewall Rules
- name: boomi-network-allow-http-ssh-rdp
  type: firewall-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    IPProtocol: TCP
    Port: [22, 80, 3389]

- name: boomi-network-allow-icmp
  type: firewall-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    IPProtocol: ICMP
    Port: []
