{% set REGION_1 = "us-central1" %}
{% set REGION_2 = "us-east4" %}
{% set REGION_3 = "europe-west2" %}

imports:
- path: customnetwork-template.jinja
- path: subnetwork-template.jinja
- path: firewall-template.jinja
- path: route-template.jinja
- path: instance-template.jinja
- path: instance_group_manager.jinja

resources:
# GCP Custom Network
- name: boomi-network
  type: customnetwork-template.jinja

# GCP Subnets (us-central, canada, uk and mumbai)
- name: boomi-public-subnet
  type: subnetwork-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    subnets:
    - name: public-subnet-1
      ipCidrRange: 10.130.0.0/20
      region: {{ REGION_1 }}
    - name: public-subnet-2
      ipCidrRange: 10.130.16.0/20
      region: us-east4
    - name: public-subnet-3
      ipCidrRange: 10.130.32.0/20
      region: europe-west2

- name: boomi-private-subnet
  type: subnetwork-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    subnets:
    - name: private-subnet-1
      ipCidrRange: 10.130.48.0/20
      region: us-central1
    - name: private-subnet-2
      ipCidrRange: 10.130.64.0/20
      region: us-east4
    - name: private-subnet-3
      ipCidrRange: 10.130.80.0/20
      region: europe-west2


# GCP Firewall Rules
- name: boomi-firewall-allow-bastion
  type: firewall-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    IPProtocol: TCP
    Port: [22, 3389]
    targetTags: bastion-machine

- name: boomi-firewall-http-https
  type: firewall-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    IPProtocol: TCP
    Port: [80, 443]

- name: boomi-firewall-allow-icmp
  type: firewall-template.jinja
  properties:
    network: $(ref.boomi-network.selfLink)
    IPProtocol: ICMP
    Port: []

- name: boomi-cloud-router
  type: route-template.jinja
  properties:
    use_custom_network: true
    network: $(ref.boomi-network.selfLink)
    subnets: 
    - region: us-central1
    - region: us-east4
    - region: us-west2

# GCP Instance
#- name: boomi-network-vm
#  type: instance-template.jinja
#  properties:
#    zone: us-central1-a
#    machineType: n1-standard-1
#    machineImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
#    network: $(ref.boomi-network.selfLink)
#    subnetwork: $(ref.private-subnet-1.selfLink)

# GCP Managed Instance Group
#- name: boomi-bastion-instance
#  type: instance_group_manager.jinja
#  properties:
#    region: us-central1
#    zone: us-central1-a
#    machineType: n1-standard-1
#    network: $(ref.boomi-network.selfLink)
#    subnetwork: $(ref.private-subnet-1.selfLink)
#    machineImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
#    targetSize: 1
