imports:
  - path: customnetwork-template.jinja
  - path: subnetwork-template.jinja
  - path: firewall-template.jinja
  
  resources:
  # GCP Custom Network
  - name: boominetwork
    type: customnetwork-template.jinja
  
  # GCP Subnets (us-central, canada, uk and mumbai)
  - name: boominetwork-subnet-us
    type: subnetwork-template.jinja
    properties:
      network: $(ref.boominetwork.selfLink)
      subnets:
        - name: private-subnet-1
          ipCidrRange: 10.130.0.0/20
          region: us-central1
  
  # GCP Firewall Rules
  - name: boominetwork-allow-http-ssh-rdp
    type: firewall-template.jinja
    properties:
      network: $(ref.boominetwork.selfLink)
      IPProtocol: TCP
      Port: [22, 80, 443]
  
  - name: boominetwork-allow-icmp
    type: firewall-template.jinja
    properties:
      network: $(ref.boominetwork.selfLink)
      IPProtocol: ICMP
      Port: []
  