imports:
- path: customnetwork-template.jinja
- path: subnetwork-template.jinja
- path: firewall-template.jinja

resources:
# GCP Custom Network
- name: network2
  type: customnetwork-template.jinja

# GCP Subnets (us-central, canada, uk and mumbai)
- name: network2-subnet-us
  type: subnetwork-template.jinja
  properties:
    ipCidrRange: 10.130.0.0/20
    network: $(ref.network2.selfLink)
    region: us-central1

# GCP Firewall Rules
- name: network2-allow-http-ssh-rdp
  type: firewall-template.jinja
  properties:
    network: $(ref.network2.selfLink)
    IPProtocol: TCP
    Port: [22, 80, 3389]

- name: network2-allow-icmp
  type: firewall-template.jinja
  properties:
    network: $(ref.network2.selfLink)
    IPProtocol: ICMP
    Port: []
