imports:
- path: customnetwork-template.jinja
- path: subnetwork-template.jinja
- path: firewall-template.jinja
- path: route-template.jinja
- path: cloud-nat-template.jinja
- path: gke-cluster-template1.jinja
- path: instance_group_manager.jinja
- path: boomi-master.jinja
  
resources:
# GCP Custom Network
- name: boomi-network
  type: boomi-master.jinja
  properties:
    region: us-central1
    zoneOne: us-central1-a
    zoneTwo: us-central1-b
    zoneThree: us-central1-c
    publicSubnetCidrRange: 10.130.0.0/20
    privateSubnetCidrRange: 10.130.16.0/20
    gkeApiVersion: v1beta1
    privatecluster: true
    bastionMachineType: f1-micro
    gkeMachineType: n1-standard-4
    minNodeCount: 1
    maxNodeCount: 15
    desiredNodeCount: 2