imports:
  - path: customnetwork-template.jinja
  - path: subnetwork-template.jinja
  - path: firewall-template.jinja
  - path: route-template.jinja
  - path: instance-template.jinja
  - path: instance_group_manager.jinja
  - path: cloud-nat-template.jinja
  - path: gke-cluster-template1.jinja
  - path: boomi-master.jinja
  
  resources:
  # GCP Custom Network
  - name: boomi-network
    type: boomi-master.jinja
    properties:
      region: us-central1
  